"""Ingest MLB play‑by‑play CSV files into the PostgreSQL warehouse.

The collector scripts (mlb_pbp_collector.py / queries.py) generate a CSV with the
column order defined in ``COLUMN_ORDER``. This script reads the CSV and copies the
rows into ``core.mlb_pbp``.

Usage::
    python ingest_mlb_pbp.py --csv path/to/file.csv

It can also be used to ingest a directory of CSVs with ``--dir``.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd
import psycopg2
from psycopg2.extras import execute_values

# ---------------------------------------------------------------------------
def _load_csv(csv_path: Path) -> pd.DataFrame:
    """Load a CSV generated by ``mlb_pbp_collector``.

    The collector writes all columns as strings; we let pandas infer dtypes and
    then convert to the appropriate Python types for the COPY operation.
    """
    return pd.read_csv(csv_path, dtype=str)

# ---------------------------------------------------------------------------
def _connect() -> psycopg2.extensions.connection:
    """Create a connection using the DATABASE_URL env var or defaults.

    The project already uses ``psql`` commands that rely on the ``DATABASE_URL``
    environment variable, so we honour that here.
    """
    import os
    db_url = os.getenv("DATABASE_URL", "postgresql://localhost/retrosheet")
    return psycopg2.connect(db_url)

# ---------------------------------------------------------------------------
def _insert_dataframe(conn, df: pd.DataFrame) -> None:
    """Insert rows into ``core.mlb_pbp`` using ``execute_values`` for speed.
    
    Resolves team names to Retrosheet team IDs using mlb.resolve_team_id function
    which handles temporal team changes (franchise moves, relocations).
    """
    # Add team ID columns if they don't exist
    if 'home_team_id' not in df.columns:
        df['home_team_id'] = None
    if 'away_team_id' not in df.columns:
        df['away_team_id'] = None
    
    # Resolve team IDs using the database function
    with conn.cursor() as cur:
        for idx, row in df.iterrows():
            game_date = row.get('game_date')
            home_team = row.get('home_team')
            away_team = row.get('away_team')
            
            if game_date and home_team:
                cur.execute(
                    "SELECT mlb.resolve_team_id(%s, %s::date)",
                    (home_team, game_date)
                )
                result = cur.fetchone()
                if result:
                    df.at[idx, 'home_team_id'] = result[0]
            
            if game_date and away_team:
                cur.execute(
                    "SELECT mlb.resolve_team_id(%s, %s::date)",
                    (away_team, game_date)
                )
                result = cur.fetchone()
                if result:
                    df.at[idx, 'away_team_id'] = result[0]
    
    # Reorder columns to put team IDs after team names
    cols = list(df.columns)
    if 'home_team_id' in cols and 'away_team_id' in cols:
        # Move team ID columns after their corresponding name columns
        home_idx = cols.index('home_team')
        away_idx = cols.index('away_team')
        cols.remove('home_team_id')
        cols.remove('away_team_id')
        cols.insert(home_idx + 1, 'home_team_id')
        cols.insert(away_idx + 2, 'away_team_id')
        df = df[cols]
    
    # Convert empty strings to None for nullable columns
    # Ensure pandas NA values are turned into None for proper NULL handling
    records = []
    for row in df.values:
        rec = []
        for v in row:
            # Convert empty strings, pandas NA, and numpy NaN to None for NULL insertion
            if v == "" or v is pd.NA or (isinstance(v, float) and pd.isna(v)):
                rec.append(None)
            else:
                rec.append(v)
        records.append(tuple(rec))
    with conn.cursor() as cur:
        sql = f"INSERT INTO core.mlb_pbp ({', '.join(cols)}) VALUES %s"
        execute_values(cur, sql, records, page_size=1000)
    conn.commit()

# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(description="Ingest MLB PBP CSVs into Postgres")
    parser.add_argument("--csv", type=str, help="Path to a single CSV file")
    parser.add_argument("--dir", type=str, help="Directory containing CSV files")
    args = parser.parse_args()

    if not args.csv and not args.dir:
        print("Specify --csv or --dir", file=sys.stderr)
        sys.exit(1)

    conn = _connect()
    try:
        if args.csv:
            df = _load_csv(Path(args.csv))
            _insert_dataframe(conn, df)
            print(f"Inserted {len(df)} rows from {args.csv}")
        else:
            for p in Path(args.dir).glob("*.csv"):
                df = _load_csv(p)
                _insert_dataframe(conn, df)
                print(f"Inserted {len(df)} rows from {p}")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
