"""Ingest MLB play-by-play CSV files into the PostgreSQL warehouse.

The collector scripts (mlb_pbp_collector.py / queries.py) generate a CSV with the
column order defined in ``COLUMN_ORDER``. This script reads the CSV and copies the
rows into ``core.mlb_pbp``.

Usage::
    python ingest_mlb_pbp.py --csv path/to/file.csv

It can also be used to ingest a directory of CSVs with ``--dir``.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import pandas as pd
import psycopg2
from psycopg2.extras import execute_values


# ---------------------------------------------------------------------------
def _load_csv(csv_path: Path) -> pd.DataFrame:
    """Load a CSV generated by ``mlb_pbp_collector``.

    The collector writes all columns as strings; we let pandas infer dtypes and
    then convert to the appropriate Python types for the COPY operation.
    """
    return pd.read_csv(csv_path, dtype=str)


# ---------------------------------------------------------------------------
def _connect() -> psycopg2.extensions.connection:
    """Create a connection using the DATABASE_URL env var or defaults.

    The project already uses ``psql`` commands that rely on the ``DATABASE_URL``
    environment variable, so we honour that here.
    """
    db_url = os.getenv('DATABASE_URL', 'postgresql://localhost/retrosheet')
    return psycopg2.connect(db_url)


# ---------------------------------------------------------------------------
def _insert_dataframe(conn, df: pd.DataFrame) -> None:
    """Insert rows into ``core.mlb_pbp`` using ``execute_values`` for speed."""
    cols = list(df.columns)
    # Convert empty strings to None for nullable columns
    records = [tuple(None if v == '' else v for v in row) for row in df.values]
    with conn.cursor() as cur:
        sql = f'INSERT INTO core.mlb_pbp ({", ".join(cols)}) VALUES %s'
        execute_values(cur, sql, records, page_size=1000)
    conn.commit()


# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(description='Ingest MLB PBP CSVs into Postgres')
    parser.add_argument('--csv', type=str, help='Path to a single CSV file')
    parser.add_argument('--dir', type=str, help='Directory containing CSV files')
    args = parser.parse_args()

    if not args.csv and not args.dir:
        print('Specify --csv or --dir', file=sys.stderr)
        sys.exit(1)

    conn = _connect()
    try:
        if args.csv:
            df = _load_csv(Path(args.csv))
            _insert_dataframe(conn, df)
            print(f'Inserted {len(df)} rows from {args.csv}')
        else:
            for p in Path(args.dir).glob('*.csv'):
                df = _load_csv(p)
                _insert_dataframe(conn, df)
                print(f'Inserted {len(df)} rows from {p}')
    finally:
        conn.close()


if __name__ == '__main__':
    main()
