-- Table to store detailed MLB play‑by‑play data from StatsAPI & Statcast
CREATE SCHEMA IF NOT EXISTS core;

CREATE TABLE IF NOT EXISTS core.mlb_pbp (
    game_pk BIGINT,
    game_date DATE,
    home_team TEXT,
    away_team TEXT,
    venue TEXT,
    retro_game_id TEXT,
    retro_event_id TEXT,
    inning INTEGER,
    inning_half TEXT,
    outs_after INTEGER,
    balls INTEGER,
    strikes INTEGER,
    batter_id BIGINT,
    batter_name TEXT,
    pitcher_id BIGINT,
    pitcher_name TEXT,
    stand TEXT,
    p_throws TEXT,
    runner_1b_id BIGINT,
    runner_2b_id BIGINT,
    runner_3b_id BIGINT,
    runner_1b TEXT,
    runner_2b TEXT,
    runner_3b TEXT,
    pitch_type TEXT,
    pitch_desc TEXT,
    release_speed DOUBLE PRECISION,
    spin_rate DOUBLE PRECISION,
    plate_x DOUBLE PRECISION,
    plate_z DOUBLE PRECISION,
    zone INTEGER,
    launch_speed DOUBLE PRECISION,
    launch_angle DOUBLE PRECISION,
    hit_distance_sc DOUBLE PRECISION,
    estimated_ba_using_speedangle DOUBLE PRECISION,
    estimated_woba_using_speedangle DOUBLE PRECISION,
    event_type TEXT,
    event_desc TEXT,
    hit_location TEXT,
    is_out BOOLEAN,
    rbi INTEGER,
    runs_scored INTEGER,
    pitch_sequence TEXT,
    retro_event_cd INTEGER,
    retro_event_code TEXT,
    retro_bat_event_fl BOOLEAN
);

CREATE INDEX IF NOT EXISTS mlb_pbp_game_idx ON core.mlb_pbp (game_pk, inning, inning_half);
CREATE INDEX IF NOT EXISTS mlb_pbp_player_idx ON core.mlb_pbp (batter_id, pitcher_id);
CREATE INDEX IF NOT EXISTS mlb_pbp_date_idx ON core.mlb_pbp (game_date);
